### ISSUE TITLE
Document  enhancement 

### ISSUE THREAD

**Issue by luoyunpeng** [eliasnaur/gophercon-uk-2019-talk#1]
Hi Elias Naur，

Sorry to bother you, i am a novice to gio, i want learn gio gui program and i learn the demo code from your Githup repo.  i  can not understand the programing mode, could you give more document about gio? 

thanks

**Comment by eliasnaur** [comment]
There is not yet a manual that connects all the programming concepts into a larger picture.

With the release of the first [design of widgets and themes](https://lists.sr.ht/~eliasnaur/gio/%3CBXNLFW0X308Y.5IPSSLZ1CM8W%40toolbox%3E), Gio is now complete enough that it's worth adding a manual. I will turn to that after the GoLab 2019 conference later this month.

In the meantime, there is the [GoDoc reference](https://godoc.org/gioui.org), my [Gophercon San Diego talk](https://github.com/eliasnaur/gophercon-2019-talk) and of course the [mailing list](https://lists.sr.ht/~eliasnaur/gio) is open for your questions.

**Comment by luoyunpeng** [comment]
Thanks
